"""Full integration tests — pairwise parametrized and Hypothesis exploration."""

import asyncio
import contextvars
import os

import pytest
from hypothesis import HealthCheck
from hypothesis import example
from hypothesis import given
from hypothesis import settings

from . import routines
from .conftest import PAIRWISE_SCENARIOS
from .conftest import BackpressureMode
from .conftest import ContextVarPattern
from .conftest import CredentialType
from .conftest import DiscoveryFactory
from .conftest import LazyMode
from .conftest import LbFactory
from .conftest import PoolMode
from .conftest import QuorumMode
from .conftest import RoutineBinding
from .conftest import RoutineShape
from .conftest import Scenario
from .conftest import TimeoutKind
from .conftest import WorkerOptionsKind
from .conftest import build_pool_from_scenario
from .conftest import default_scenario
from .conftest import invoke_routine
from .conftest import scenarios_strategy

_INTEGRATION_TIMEOUT = 30

# The Hypothesis exploration is load-sensitive: a heavy example on a
# busy machine can overrun the 30s bound the pairwise cases run under,
# and the resulting asyncio.timeout cancellation strands live workers in
# pool teardown (#294). It gets its own, looser bound rather than
# sharing one.
_HYPOTHESIS_TIMEOUT = 90


@pytest.mark.integration
def test_pairwise_scenarios_cover_all_discovery_members():
    """Test the covering array exercises every discovery factory.

    Given:
        The pairwise covering array generated by allpairspy plus its
        pinned backstop scenarios.
    When:
        The discovery members appearing across all scenarios are
        collected.
    Then:
        It should include every DiscoveryFactory member — allpairspy's
        greedy placement can silently drop feasible members under
        heavy filter constraints.
    """
    # Act
    covered = {scenario.discovery for scenario in PAIRWISE_SCENARIOS}

    # Assert
    assert covered == set(DiscoveryFactory)


@pytest.mark.integration
@pytest.mark.asyncio
@pytest.mark.parametrize("scenario", PAIRWISE_SCENARIOS, ids=str)
async def test_dispatch_pairwise(scenario, credentials_map, retry_grpc_internal):
    """Test routine dispatch across pairwise scenario combinations.

    Given:
        A complete scenario from the pairwise covering array.
    When:
        A pool is built and the appropriate routine is dispatched.
    Then:
        It should return the expected result for the given routine shape.
    """

    # Arrange, act, & assert
    async def body():
        async with asyncio.timeout(_INTEGRATION_TIMEOUT):
            async with build_pool_from_scenario(scenario, credentials_map):
                # Each invocation runs in an isolated stdlib Context
                # copy. pytest-asyncio re-uses a single ``context=``
                # across every test invocation, so mutations made
                # inside ``invoke_routine`` otherwise leak into the
                # shared context and cross-contaminate other
                # parametrized cases. See pytest-asyncio #136 /
                # AnyIO testing docs for the known interaction
                # between pytest runners, ``asyncio.Task(context=)``
                # and ContextVar mutation visibility.
                isolated = contextvars.copy_context()
                await asyncio.create_task(invoke_routine(scenario), context=isolated)

    await retry_grpc_internal(body)


@pytest.mark.integration
@pytest.mark.asyncio
@settings(
    max_examples=50,
    deadline=None,
    suppress_health_check=[
        HealthCheck.function_scoped_fixture,
        HealthCheck.too_slow,
    ],
)
@example(
    scenario=Scenario(
        RoutineShape.COROUTINE,
        PoolMode.DEFAULT,
        DiscoveryFactory.NONE,
        LbFactory.CLASS_REF,
        CredentialType.INSECURE,
        WorkerOptionsKind.DEFAULT,
        TimeoutKind.NONE,
        RoutineBinding.MODULE_FUNCTION,
        LazyMode.LAZY,
        BackpressureMode.NONE,
        ContextVarPattern.NONE,
        ContextVarPattern.NONE,
        ContextVarPattern.NONE,
        QuorumMode.DEFAULT,
    )
)
@example(
    scenario=Scenario(
        RoutineShape.ASYNC_GEN_ANEXT,
        PoolMode.EPHEMERAL,
        DiscoveryFactory.NONE,
        LbFactory.INSTANCE,
        CredentialType.INSECURE,
        WorkerOptionsKind.DEFAULT,
        TimeoutKind.NONE,
        RoutineBinding.MODULE_FUNCTION,
        LazyMode.LAZY,
        BackpressureMode.SYNC,
        ContextVarPattern.NONE,
        ContextVarPattern.NONE,
        ContextVarPattern.NONE,
        QuorumMode.DEFAULT,
    )
)
@example(
    scenario=Scenario(
        RoutineShape.COROUTINE,
        PoolMode.DEFAULT,
        DiscoveryFactory.NONE,
        LbFactory.CLASS_REF,
        CredentialType.INSECURE,
        WorkerOptionsKind.KEEPALIVE,
        TimeoutKind.NONE,
        RoutineBinding.MODULE_FUNCTION,
        LazyMode.LAZY,
        BackpressureMode.ASYNC,
        ContextVarPattern.NONE,
        ContextVarPattern.NONE,
        ContextVarPattern.NONE,
        QuorumMode.DEFAULT,
    )
)
@given(scenario=scenarios_strategy())
async def test_dispatch_hypothesis(scenario, credentials_map, retry_grpc_internal):
    """Test routine dispatch with Hypothesis-generated scenarios.

    Given:
        A randomly generated valid scenario from the Hypothesis strategy.
    When:
        A pool is built and the appropriate routine is dispatched.
    Then:
        It should return the expected result for the given routine shape.
    """

    # Arrange, act, & assert
    async def body():
        async with asyncio.timeout(_HYPOTHESIS_TIMEOUT):
            async with build_pool_from_scenario(scenario, credentials_map):
                # See ``test_dispatch_pairwise`` above for the
                # rationale behind isolating each Hypothesis example
                # in its own stdlib Context copy.
                isolated = contextvars.copy_context()
                await asyncio.create_task(invoke_routine(scenario), context=isolated)

    await retry_grpc_internal(body)


@pytest.mark.integration
class TestNestedDispatch:
    @pytest.mark.asyncio
    async def test_nested_pid_fanout_should_dispatch_to_the_pool(
        self, credentials_map, retry_grpc_internal
    ):
        """Test nested dispatches fan out to pool workers, not the outer process.

        Given:
            An EPHEMERAL pool with two eagerly started workers
            (quorum 2) and a routine that reports its own pid plus the
            pids of four nested `get_pid` dispatches.
        When:
            The caller dispatches the fan-out routine.
        Then:
            The outer pid should differ from the caller's pid, every
            inner pid should differ from the caller's pid, and the four
            inner pids should span both pool workers — nested dispatches
            go through the round-robin pool rather than self-executing.
        """

        # Arrange, act, & assert
        async def body():
            scenario = default_scenario(
                pool_mode=PoolMode.EPHEMERAL,
                lazy=LazyMode.EAGER,
                quorum=QuorumMode.ABOVE_DEFAULT,
            )
            # The same bound every sibling in this module runs under.
            # Without it, a worker child that wedges before reporting
            # its metadata hangs pool entry — and this test — forever.
            async with asyncio.timeout(_INTEGRATION_TIMEOUT):
                async with build_pool_from_scenario(scenario, credentials_map):
                    outer_pid, inner_pids = await routines.nested_pid_fanout(4)
            caller_pid = os.getpid()
            assert outer_pid != caller_pid
            assert all(pid != caller_pid for pid in inner_pids)
            assert len(set(inner_pids)) == 2

        await retry_grpc_internal(body)
