name: Bug Report
description: Report something that isn't working correctly.
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the bug? Include steps to reproduce if applicable.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: root-cause
    attributes:
      label: Root cause
      description: What is causing the bug? Include relevant code snippets.
    validations:
      required: false
