name: Test
description: Add or improve test coverage or test infrastructure.
labels: ["test"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What needs to be tested or what test infrastructure is needed?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this test work needed? What gap does it fill?
    validations:
      required: true
  - type: textarea
    id: affected-code
    attributes:
      label: Affected code
      description: Which files, modules, or components are affected?
    validations:
      required: false
