import pathlib
import re
import tomllib

from wool.protocol import wire_pb2
from wool.protocol import wire_pb2_grpc

_PYPROJECT = pathlib.Path(__file__).parents[2] / "pyproject.toml"
_NAME = re.compile(r"\s*([A-Za-z0-9][A-Za-z0-9._-]*)")
_FLOOR = re.compile(r">=\s*([0-9][0-9A-Za-z.+!*-]*)")
_PROTOBUF_GENCODE = re.compile(
    r"ValidateProtobufRuntimeVersion\(\s*[^,]+,\s*(\d+),\s*(\d+),\s*(\d+)",
    re.DOTALL,
)


def _declared_floor(distribution: str) -> str:
    with _PYPROJECT.open("rb") as handle:
        dependencies = tomllib.load(handle)["project"]["dependencies"]
    for dependency in dependencies:
        name_match = _NAME.match(dependency)
        if name_match and name_match.group(1).lower() == distribution.lower():
            floor_match = _FLOOR.search(dependency)
            assert floor_match, f"{distribution} declares no '>=' floor"
            return floor_match.group(1)
    raise AssertionError(f"{distribution} is not a declared dependency")


def _protobuf_gencode_version() -> str:
    source = pathlib.Path(wire_pb2.__file__).read_text(encoding="utf-8")
    match = _PROTOBUF_GENCODE.search(source)
    assert match, "no ValidateProtobufRuntimeVersion assertion in wire_pb2"
    return ".".join(match.groups())


def test_grpc_generated_version_matches_declared_grpcio_floor():
    """Test the gRPC stub's embedded version equals the declared grpcio floor.

    Given:
        The wire gRPC stub generated by the pinned codegen toolchain.
    When:
        Its embedded GRPC_GENERATED_VERSION is compared to the grpcio lower
        bound declared in pyproject.
    Then:
        It should match exactly, so the advertised floor is the version the
        shipped stub actually requires.
    """
    assert wire_pb2_grpc.GRPC_GENERATED_VERSION == _declared_floor("grpcio")


def test_protobuf_gencode_version_matches_declared_protobuf_floor():
    """Test the protobuf gencode version equals the declared protobuf floor.

    Given:
        The wire protobuf stub generated by the pinned codegen toolchain.
    When:
        Its embedded ValidateProtobufRuntimeVersion gencode version is compared
        to the protobuf lower bound declared in pyproject.
    Then:
        It should match exactly, so the advertised floor is the version the
        shipped stub actually requires.
    """
    assert _protobuf_gencode_version() == _declared_floor("protobuf")
