name: Run tests

on:
  pull_request:
    branches:
      - main
      - master
      - release

concurrency:
  group: run-tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    name: Detect code changes
    runs-on: ubuntu-latest
    outputs:
      has_code_changes: ${{ steps.get-touched-files.outputs.touched && 'true' || 'false' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get touched files
        id: get-touched-files
        uses: ./.github/actions/get-touched-files
        with:
          pathspec: 'wool/src/ wool/tests/ wool/pyproject.toml proto/ .github/'

  lint:
    name: Lint / pyright
    needs: detect-changes
    if: needs.detect-changes.outputs.has_code_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv and prepare python
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.13'

      - name: Install packages
        run: |
          .github/scripts/install-python-packages.sh
          uv pip install -e './wool[dev]'

      - name: Run pyright
        run: |
          cd wool
          uv run pyright

  unit-tests:
    name: Unit / Python ${{ matrix.python-version }}
    needs: detect-changes
    if: needs.detect-changes.outputs.has_code_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        namespace: ['wool']
        python-version: ['3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-tests
        with:
          python-version: ${{ matrix.python-version }}
          namespace: ${{ matrix.namespace }}
          pytest-marker: not integration
          cov-fail-under: '98'

  integration-tests:
    name: Integration / Python ${{ matrix.python-version }}
    needs: [detect-changes, unit-tests]
    if: needs.detect-changes.outputs.has_code_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        namespace: ['wool']
        python-version: ['3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-tests
        with:
          python-version: ${{ matrix.python-version }}
          namespace: ${{ matrix.namespace }}
          pytest-marker: integration
          cov-fail-under: '70'
