name: Validate pull request

on:
  pull_request:
    branches:
      - master
      - main
      - release
    types:
      - edited
      - opened
      - reopened
      - synchronize
    paths:
      - src/**
      - pyproject.toml
    
jobs:
  merge-forbidden:
    name: Merge forbidden
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'master' && github.head_ref != 'release' }}
    steps:
      - run: |
          echo "ERROR: Merging code changes directly into master forbidden."
          exit 1
