name: Validate repository
description: Confirm that the required secrets are defined in the repository

on:
  workflow_dispatch:
    
jobs:
  validate-secrets:
    name: Validate secrets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        secret_name: [MY_TOKEN, PYPI_TOKEN]
    steps:
      - name: Check ${{ matrix.secret_name }} secret
        env:
          SECRET_VALUE: ${{ secrets[matrix.secret_name] }}
        if: ${{ env.SECRET_VALUE == '' }}
        run: |
          echo 'The secret "${{ matrix.secret_name }}" has not been defined'
          echo 'Go to "settings \> secrets \> actions" to define it'
          exit 1
